### ISSUE TITLE
http://localhost:8080/api/products/jewelrys return empty when Jewelrys table has data

### ISSUE THREAD

**Issue by MaGaoju** [huangcu/heshi#7]
which table ?

select * from heshi_dev.jewelrys  I have upload some data in this table, but got "null" with API http://localhost:8080/api/products/jewelrys
@huangcu

**Comment by huangcu** [comment]
/api/products/jewelrys retrieve all jewelrys, it will return null if no data. 
make sure your table has data, do a "select * from jewelrys;" first.
